version: "2"

networks:
    db-net-bupi:
      external:
        name: db-net-bupi

services:

  #db:
   # container_name: "psql"
    #image: kartoza/postgis
    #ports:
    #  - "49155:5432"
    #environment:
    #  POSTGRES_USER: docker
    #  POSTGRES_PASS: docker
    #volumes:
     # - pg_data:/var/lib/postgresql

  web:
    container_name: "bupi-containner"
    build: .
    ports:
        - "3005:3000"
    #links:
     #   - postgis
    #depends_on:
    #    - db
    networks:
        - db-net-bupi
    volumes:
       - /app/repositorio/_data:/app/repositorio

volumes:
    repositorio: